scrape_configs:
  - job_name: 'temperature-exporter'
    scrape_interval: 1s
    static_configs:
    - targets: ['host.docker.internal:5000']
      labels:
        instance: 'pizero'
        room: 'basement'

